
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-01
owner: ucsb-cs156-f25
repo_name: team01-f25-01
pull_requests: [{"author":{"id":"U_kgDOCl4-hw","is_bot":false,"login":"ngostream","name":"Nathan Ngo"},"headRefName":"nn-delete-endpoint-UCSBDiningCommonsMenuItems","number":56,"title":"nn - add delete endpoint for UCSBDiningCommonsMenuItems","url":"https://github.com/ucsb-cs156-f25/team01-f25-01/pull/56"},{"author":{"id":"U_kgDOCl4-hw","is_bot":false,"login":"ngostream","name":"Nathan Ngo"},"headRefName":"nn-put-endpoint-UCSBDiningCommonsMenuItems","number":54,"title":"nn - put endpoint for single record: ucsb dining commons menu items","url":"https://github.com/ucsb-cs156-f25/team01-f25-01/pull/54"}]
