
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-01
owner: ucsb-cs156-f25
repo_name: team01-f25-01
pull_requests: [{"author":{"id":"U_kgDOCSk7nw","is_bot":false,"login":"jjohnvu","name":""},"headRefName":"jvu-helprequest-controller","number":74,"title":"Jvu helprequest controller","url":"https://github.com/ucsb-cs156-f25/team01-f25-01/pull/74"},{"author":{"id":"U_kgDOBkhdrg","is_bot":false,"login":"nicxs3","name":"Nic Santos"},"headRefName":"ns-Articles-create-controller","number":73,"title":"ns - create Articles controller and GET/POST","url":"https://github.com/ucsb-cs156-f25/team01-f25-01/pull/73"},{"author":{"id":"U_kgDOCO5ODw","is_bot":false,"login":"noahzlouie","name":"Noah Louie"},"headRefName":"nl-create-MenuItemReview-ctr","number":72,"title":"nl -  create menu item review ctr","url":"https://github.com/ucsb-cs156-f25/team01-f25-01/pull/72"},{"author":{"id":"U_kgDOCSk7nw","is_bot":false,"login":"jjohnvu","name":""},"headRefName":"jjohnvu-helprequest-entity","number":67,"title":"jv - Create database table for HelpRequest","url":"https://github.com/ucsb-cs156-f25/team01-f25-01/pull/67"}]
