
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-01
owner: ucsb-cs156-f25
repo_name: team01-f25-01
pull_requests: [{"author":{"id":"U_kgDOCl4-hw","is_bot":false,"login":"ngostream","name":"Nathan Ngo"},"headRefName":"nn-UCSBDiningCommonsMenuItem-create-UCSBDiningCommonsMenuItemController","number":51,"title":"nn - create ucsb dining commons menu item controller with get and post","url":"https://github.com/ucsb-cs156-f25/team01-f25-01/pull/51"},{"author":{"id":"U_kgDOBwqWJQ","is_bot":false,"login":"WLL1am","name":"William Chung"},"headRefName":"wc-put-for-recommendationrequests-table","number":50,"title":"Wc - put for recommendationrequests table","url":"https://github.com/ucsb-cs156-f25/team01-f25-01/pull/50"},{"author":{"id":"U_kgDOBwqWJQ","is_bot":false,"login":"WLL1am","name":"William Chung"},"headRefName":"wc-recommendationrequests-get-by-id","number":49,"title":"Wc - add GET by id for recommendation requests","url":"https://github.com/ucsb-cs156-f25/team01-f25-01/pull/49"},{"author":{"id":"U_kgDOBwqWJQ","is_bot":false,"login":"WLL1am","name":"William Chung"},"headRefName":"wc-create-recommendationrequest-controller","number":48,"title":"wc - create RecommendationRequests Controller","url":"https://github.com/ucsb-cs156-f25/team01-f25-01/pull/48"}]
