
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-01
owner: ucsb-cs156-f25
repo_name: team01-f25-01
pull_requests: [{"author":{"id":"U_kgDOB7yQrQ","is_bot":false,"login":"WilliamLinA","name":""},"headRefName":"yl-UCSBOrganizations-delete","number":71,"title":"yl - add DELETE method and test","url":"https://github.com/ucsb-cs156-f25/team01-f25-01/pull/71"},{"author":{"id":"U_kgDOBkhdrg","is_bot":false,"login":"nicxs3","name":"Nic Santos"},"headRefName":"ns-Articles-create-controller","number":69,"title":"Ns articles create controller","url":"https://github.com/ucsb-cs156-f25/team01-f25-01/pull/69"},{"author":{"id":"U_kgDOCSk7nw","is_bot":false,"login":"jjohnvu","name":""},"headRefName":"jjohnvu-helprequest-entity","number":67,"title":"jv - Create database table for HelpRequest","url":"https://github.com/ucsb-cs156-f25/team01-f25-01/pull/67"}]
