
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-01
owner: ucsb-cs156-f25
repo_name: team01-f25-01
pull_requests: [{"author":{"id":"U_kgDOCSk7nw","is_bot":false,"login":"jjohnvu","name":""},"headRefName":"jjohnvu-helprequest-entity","number":67,"title":"Add HelpRequest entity, repository, and migration file","url":"https://github.com/ucsb-cs156-f25/team01-f25-01/pull/67"},{"author":{"id":"U_kgDOCO5ODw","is_bot":false,"login":"noahzlouie","name":"Noah Louie"},"headRefName":"nl-create-MenuItemReview-ctr","number":65,"title":"nl -  create menu item review ctr","url":"https://github.com/ucsb-cs156-f25/team01-f25-01/pull/65"},{"author":{"id":"U_kgDOBwqWJQ","is_bot":false,"login":"WLL1am","name":"William Chung"},"headRefName":"wc-update-readme-links-titles","number":62,"title":"wc - changed readme with updated links and titles","url":"https://github.com/ucsb-cs156-f25/team01-f25-01/pull/62"}]
